name: Final Dispatch Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on:
      - self-hosted
      - Windows
      - X64
      - leninkart
      - local
      - dev

    steps:
      - name: Validate runner
        shell: cmd
        run: echo Dispatch working
